import { Skill } from '../types/Profile'

export const SKILLS: Partial<Skill>[] = [
  { name: 'Adaptability', type: 'personal' },
  { name: 'Communication', type: 'personal' },
  { name: 'Creativity', type: 'personal' },
  { name: 'Dependability', type: 'personal' },
  { name: 'Interpersonal Skills', type: 'personal' },
  { name: 'Leadership', type: 'personal' },
  { name: 'Professionalism', type: 'personal' },
  { name: 'Self Awareness', type: 'personal' },
  { name: 'Teamwork', type: 'personal' },
  { name: 'Willingness to Learn', type: 'personal' },
  { name: 'Other', type: 'personal' },
  { name: 'Math basics', type: 'technical' },
  { name: 'Physically able', type: 'technical' },
  { name: 'Digital Technology Basics', type: 'technical' },
  { name: 'Customer Service', type: 'technical' },
  { name: 'Marketing/Sales', type: 'technical' },
  { name: 'Accounting/Budgeting', type: 'technical' },
  { name: 'Blueprint Reading', type: 'technical' },
  { name: 'Computer Basics', type: 'technical' },
  { name: 'Conflict Management', type: 'technical' },
  { name: 'Mechanical Aptitude', type: 'technical' },
  { name: 'Negotiation', type: 'technical' },
  { name: 'Reading & Writing', type: 'technical' },
  { name: 'Time Management', type: 'technical' },
  { name: 'Web Development', type: 'technical' },
  { name: 'Other', type: 'technical' },
]
