# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on:
      group: organization/Default

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Checkout Skillarc GH action
        uses: actions/checkout@v4
        with:
          repository: SkillArc-App/skillarc-ci-action
          ref: v0.1.4
          ssh-key: ${{ secrets.SKILLARC_CI_ACTION_ACCESS }}
          path: .github/actions/skillarc-ci-action
      - name: Run SkillArc GH action
        uses: ./.github/actions/skillarc-ci-action
        with:
          alert_threshold: 120
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Next Cache
        uses: actions/cache@v4
        with:
          # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key:
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{
            hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: npm ci
      - run: npm run build
  lint:
    runs-on:
      group: organization/Default

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  test:
    runs-on:
      group: organization/Default

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test
  e2e:
    runs-on:
      group: organization/Default

    permissions: read-all

    strategy:
      matrix:
        node-version: [20.x]

    services:
      redis:
        image: 'redis:7.2.1-alpine'
        ports:
          - '127.0.0.1:6379:6379'
      postgres:
        image: postgres:15.3-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: dev
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      resque:
        image: ghcr.io/skillarc-app/resque:latest
        env:
          SLACK_GATEWAY_STRATEGY: 'fake'
          MOCK_AUTH: 'true'
          POSTGRES_HOST: 'postgres'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_PORT: 5432
          REDIS_URL: 'redis://redis:6379'
          SMS_GATEWAY_STRATEGY: fake
          KLAVIYO_API_KEY: 'fake'
        credentials:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      server:
        image: ghcr.io/skillarc-app/server:latest
        ports:
          - 3001:3001
        env:
          SLACK_GATEWAY_STRATEGY: 'fake'
          MOCK_AUTH: 'true'
          POSTGRES_HOST: 'postgres'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_PORT: 5432
          REDIS_URL: 'redis://redis:6379'
          SMS_GATEWAY_STRATEGY: fake
          KLAVIYO_API_KEY: 'fake'
          CI: true
        credentials:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    env:
      MOCK_AUTH: 'true'
      RAILS_ENV: test
      DATABASE_URL: 'postgres://rails:password@localhost:5432/rails_test'
      SLACK_GATEWAY_STRATEGY: fake
      NEXT_PUBLIC_MOCK_NEXT_AUTH: true
      NEXT_PUBLIC_API_URL: http://localhost:3001
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
      - run: |
          docker ps
          container_name=$(docker ps --filter "ancestor=ghcr.io/skillarc-app/server:latest" --format "{{.Names}}" | head -n 1)
          echo "Container name: $container_name"
          docker exec "$container_name" bin/rails db:reset
      - name: Checkout Skillarc GH action
        uses: actions/checkout@v4
        with:
          repository: SkillArc-App/skillarc-ci-action
          ref: v0.1.4
          ssh-key: ${{ secrets.SKILLARC_CI_ACTION_ACCESS }}
          path: .github/actions/skillarc-ci-action
      - name: Run SkillArc GH action
        uses: ./.github/actions/skillarc-ci-action
        with:
          alert_threshold: 300
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Run Client for E2E Tests
        run: npm run dev & sleep 5 && curl http://localhost:3000 -I
      - name: Run Cypress
        run: npm run cypress:run
